# Generated by Django 6.0 on 2025-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/'),
        ),
    ]
